### ISSUE TITLE
Crashing on clicking menu

### ISSUE THREAD

**Issue by PatilShreyas** [saket/cascade#5]
Device: Xiaomi Redmi Note 4
Android Version: API 24

I installed sample application on my device. Clicked on menu icon and it crashed.

Here are logs

```
java.lang.NoSuchMethodError: No virtual method getFont(I)Landroid/graphics/Typeface; in class Landroid/content/res/Resources; or its super classes (declaration of 'android.content.res.Resources' appears in /system/framework/framework.jar)
	at me.saket.cascade.sample.MainActivity$cascadeMenuStyler$3.invoke(MainActivity.kt:103)
	at me.saket.cascade.sample.MainActivity$cascadeMenuStyler$3.invoke(MainActivity.kt:27)
	at me.saket.cascade.CascadeMenuAdapter.onBindViewHolder(CascadeMenuAdapter.kt:70)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
	at android.view.View.measure(View.java:19762)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6122)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:19762)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6122)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:19762)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2315)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1402)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1651)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1290)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6399)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
	at android.view.Choreographer.doCallbacks(Choreographer.java:685)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6375)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

I hope this information would be helpful for you.

**Comment by saket** [comment]
Huh I wonder if this line is using an API that isn't available on level 24.

https://github.com/saket/cascade/blob/e8a93b15017cd0af292a196b58f85d34b172c60c/app/src/main/java/me/saket/cascade/sample/MainActivity.kt#L99

Wanna send a PR?
